## Lab - Matrices

Create the following matrices...

$A = \left[\begin{array}{cc}10 & 95 & 8 \\ 95 & 20 & 9 \\ 8 & 9 & 30\end{array}\right]$

$B = \left[\begin{array}{cc}5 & 8 & 3 & 6\\ 95 & 20 & 9 & 3\\ 8 & 9 & 30 & 3\\ 8 & 9 & 30 & 3\end{array}\right]$

$C = \left[\begin{array}{cc}0 & 6 & 250 \\ -6 & 0 & 86.3 \\ -250 & -86.3 & 0\end{array}\right]$

...calculate...

1. Transpose of A,B and C
2. Inverse of A, B and C

...answer the following...

* What type of matrices are A, B and C

...and perform the below given operations

1. Add A and B. Is the additive result a special type of matrix? If yes, then what type of matrix is it?
2. Multiply A and B. Is the product a special type of matrix? If yes, then what type of matrix is it?

In [1]:
import numpy as np

A = np.array([[10,95,8],[95,20,9],[8,9,30]])
B = np.array([[5,8,3,6],[95,20,9,3],[8,9,30,3],[8,9,30,3]])
C = np.array([[0,6,250],[-6,0,86.3],[-250,-86.3,0]])

print(A)
print(B)
print(C)

[[10 95  8]
 [95 20  9]
 [ 8  9 30]]
[[ 5  8  3  6]
 [95 20  9  3]
 [ 8  9 30  3]
 [ 8  9 30  3]]
[[   0.     6.   250. ]
 [  -6.     0.    86.3]
 [-250.   -86.3    0. ]]


In [2]:
A_trans = np.transpose(A)
B_trans = np.transpose(B)
C_trans = np.transpose(C)

print(A_trans)
print(B_trans)
print(C_trans)

[[10 95  8]
 [95 20  9]
 [ 8  9 30]]
[[ 5 95  8  8]
 [ 8 20  9  9]
 [ 3  9 30 30]
 [ 6  3  3  3]]
[[   0.    -6.  -250. ]
 [   6.     0.   -86.3]
 [ 250.    86.3    0. ]]


In [9]:
A_inv = np.linalg.inv(A)
#B_inv = np.linalg.inv(B)
#C_inv = np.linalg.inv(C)

print(A_inv)
#print(B_inv)
#print(C_inv)

[[-0.00205009  0.0109733  -0.0027453 ]
 [ 0.0109733  -0.00093222 -0.00264655]
 [-0.0027453  -0.00264655  0.03485938]]


In [10]:
B_inv = np.linalg.inv(B)

LinAlgError: Singular matrix

In [11]:
C_inv = np.linalg.inv(C)

LinAlgError: Singular matrix

## A is Symmetric. B and C are Singular.