## Numpy Lab 1 

Write a python program that creates two arrays with the following description:

1. Array 'a' - is a 3*3 array and has numbers from 10 to 46 with equal space between.
2. Array 'b' is a 3*2 array and has number 60 to 180 with equal space between each element.
3. Create a new array 'c' and assign it with the result of multiplication of Arrays - a *  b

Hint: Refer to numpy documentation at  https://docs.scipy.org/doc/numpy/user/quickstart.html

In [12]:
import numpy as np
a = np.array(np.arange(10,46,4).reshape(3,3))
a

array([[10, 14, 18],
       [22, 26, 30],
       [34, 38, 42]])

In [8]:
b = np.array(np.arange(60,180,20).reshape(3,2))
b

array([[ 60,  80],
       [100, 120],
       [140, 160]])

In [13]:
c = np.matmul(a,b)
c

array([[ 4520,  5360],
       [ 8120,  9680],
       [11720, 14000]])