## Numpy Lab 2

Create a numpy array A of shape 3*3 with random values from 100 to 300 and modify the array such that:

1. If an element of array A is greater than 200% of the minimum value in the array, then reduce the value by half.
2. Further if an element of array A is less than 50% of the maximum value, then increase the value by 50%. 
3. Assign the resultant array to B 

Hint: Refer to numpy documentation at  https://docs.scipy.org/doc/numpy/user/quickstart.html

In [57]:
import numpy as np

np.random.seed(5)
A = np.random.randint(100,300,(3,3))
A

array([[199, 289, 218],
       [244, 173, 108],
       [290, 255, 212]])

In [58]:
a = np.array([i/2 if i>2*np.amin(A) else i for j in A for i in j]).reshape(3,3)
a

array([[199. , 144.5, 109. ],
       [122. , 173. , 108. ],
       [145. , 127.5, 212. ]])

In [59]:
B = np.array([3*i/2 if i<np.amax(A)/2 else i for j in a for i in j]).reshape(3,3)
B

array([[199.  , 216.75, 163.5 ],
       [183.  , 173.  , 162.  ],
       [145.  , 191.25, 212.  ]])